### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by arushibutan11** [arushibutan11/OSM#1]
- [x] Convert "created at" to python DateTime format

- [ ] Add two classifiers before entry of tweet in Database. 

- [x] Add additional fields like date, time, status, department, actionable/non-actionable at time of entry. 

- [ ] Add a background daemon process(preferably using Celery)

- [ ] Check Timezone offset 

- [ ] Automatic updation - Ajax?

- [x] Tweets order - latest first.
